name: Main

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: yarn
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v7
      - name: Build from src
        run: yarn build
      - name: Test
        run: yarn test
